version: '3.8'

services:
  graphql-api:
    user: node
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/api
    container_name: graphql-api-todo
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@graph-db:5432/jesttest
      - JWT_SECRET_KEY=mem
    command: [ "npm", "run", "start:dev" ]
    ports:
      - '4001:4001'
    networks:
      - graph-network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: graph-db
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - graph-network
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  graph-network:
    driver: bridge

volumes:
  postgres:
    driver: local
